### PR TITLE
#29 set rectangle pois

### LINKED ISSUE #29: Set POI Rectangles on the generated Route
Should be done after #27

### LINKED ISSUE #48: Replace NoSuchElementException in POIParser
Maybe its not the best to throw an `NoSuchElementException` when a bbox contains no POI nodes. Its not that unusual that this can happen so this should be treated without an Exception.

See: [POIParser](https://github.com/pnancke/trip-planner/blob/master/grails-app/controllers/trip/planner/POIParser.groovy#L42)

### LINKED ISSUE #51: Improve Types
- use Interface Types (such as List instead of ArrayList)
- Instead of use `Pair<Double,Double>` please use the `Point` type to simplify the code.
- for the json response of the route a `List<List<String>> ` is neccesary but ugly, write a method for the mapping to a better type (e.g.: `List<Point>`)

### PR DESCRIPTION
**Pull request by MZober1993**
closes #29 
closes #48 
closes #51

### CODE REVIEW

File: grails-app/controllers/trip/planner/osm/api/Api.groovy [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package trip.planner.osm.api
+
+
+interface Api {
+    /**
+     *
+     * @return success - if the NominationApi xmlContent is valid or not
+     */
+    boolean doRequest()
+}
```
Comment (pnancke) [inline grails-app/controllers/trip/planner/osm/api/Api.groovy]: Please add a blanc line.
